# Default values for opcsimulator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

mqBrokerEndpoint: "insecure-mq-listener.azure-iot-operations.svc.cluster.local"
mqBrokerEndpointPort: "1883"