apiVersion: apps/v1
kind: Deployment
metadata:
  name: mqtt-simulator-deployment
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: "mqtt"
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mqtt-simulator
  template:
    metadata:
      labels:
        app: mqtt-simulator
    spec:
      containers:
        - name: mqtt-simulator
          image: ghcr.io/mrhoads/mqtt-publisher:0.0.2
          args:
            - --broker
            - {{ .Values.mqBrokerEndpoint }}
            - --port
            - {{ .Values.mqBrokerEndpointPort | quote }}
            - --topic
            - robot/data
            - --file
            - data/sampledata.csv
            - --loop